# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MultiTableView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MultiTableView
pod 'RxSwift'
pod 'RxCocoa'




  target 'MultiTableViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MultiTableViewUITests' do
    # Pods for testing
  end

end
